### ISSUE TITLE
Does not need menu item

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-notifications#2]
Notifications should not register a menu item.

**Comment by afaikafk** [comment]
Dropped in 609437642227bf4bef5f695d0dc3a21b1ab7e6ef

**Comment by foxbunny** [comment]
After pulling from master, and restarting Librarian, I get the following tb:

```
Traceback (most recent call last):
  File "/home/hajime/.envs/libtest/bin/librarian", line 9, in <module>
    load_entry_point('librarian==0.5.dev1', 'console_scripts', 'librarian')()
  File "/home/hajime/code/librarian/librarian/app.py", line 29, in main
    supervisor = Supervisor(root_dir)
  File "/home/hajime/code/librarian-core/librarian_core/supervisor.py", line 67, in __init__
    self.events.publish(self.INIT_COMPLETE, self)
  File "/home/hajime/code/librarian-core/librarian_core/pubsub.py", line 40, in publish
    listener(*args, **kwargs)
  File "/home/hajime/code/librarian-menu/librarian_menu/hooks.py", line 9, in init_complete
    supervisor.exts.menuitems.sort(supervisor.config)
  File "/home/hajime/code/librarian-menu/librarian_menu/registry.py", line 45, in sort
    raise MenuItemNotFound(item_name)
librarian_menu.registry.MenuItemNotFound: notifications
```

**Comment by afaikafk** [comment]
The menu item is referenced in `config.ini` most likely in librarian-ui

**Comment by foxbunny** [comment]
Hm, right, I thought we no longer used the config for the menu. My bad. Closing.
